#!/bin/bash
case $1 in
	up)
		psql stillebot -c "set default_transaction_read_only = false; notify readonly, 'off';"
	;;
	dn|down)
		psql stillebot -c "set default_transaction_read_only = true; notify readonly, 'on';"
	;;
	stat|status)
		psql stillebot -c "
			select client_addr, application_name, backend_start, xact_start, state from pg_stat_activity where usename = 'rosuav' and pid != pg_backend_pid();
			select client_addr, application_name, query from pg_stat_activity where usename = 'rosuav' and pid != pg_backend_pid();
			show default_transaction_read_only;
		"
	;;
	*)
		echo "Usage: $0 up|dn|status"
	;;
esac
